# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='charts',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user_charts',
            field=models.ManyToManyField(to='apis.Chart'),
        ),
    ]
