# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20160215_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='user_charts',
            new_name='charts',
        ),
        migrations.AlterField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
