# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 8, 17, 51, 4, 239797, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 8, 17, 51, 11, 31078, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
