# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20160208_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=1)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Api')),
            ],
        ),
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChartVisualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.AddField(
            model_name='charttype',
            name='chartVisualization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.ChartVisualization'),
        ),
        migrations.AddField(
            model_name='chart',
            name='chartType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.ChartType'),
        ),
    ]
