# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20160216_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='api',
            new_name='apis',
        ),
    ]
