# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20160210_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 10, 18, 8, 53, 368006, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 10, 18, 9, 3, 481389, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 2, 10, 18, 9, 8, 329401, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 10, 18, 9, 14, 626527, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 10, 18, 9, 19, 415992, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 2, 10, 18, 9, 23, 666157, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charttype',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 10, 18, 9, 37, 310040, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charttype',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 10, 18, 9, 48, 224313, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartvisualization',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 10, 18, 9, 54, 239959, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartvisualization',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 10, 18, 9, 58, 403054, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
