# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20160216_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort', models.PositiveSmallIntegerField()),
                ('call', models.CharField(max_length=100)),
            ],
        ),
    ]
