# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20160210_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default', models.BooleanField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('user', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Chart')),
            ],
        ),
    ]
