# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
