# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='default',
            field=models.BooleanField(default=0),
        ),
    ]
