# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20160211_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charttable',
            name='attribute',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='charttable',
            name='dataSetName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='charttable',
            name='dimensions',
            field=models.CharField(max_length=50),
        ),
    ]
