# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20160211_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charttable',
            name='size',
            field=models.CharField(choices=[('1', '1x'), ('2', '2x'), ('3', '3x')], max_length=2, verbose_name='size of your chart'),
        ),
    ]
