# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20160211_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartTable',
            new_name='Chart',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='dataSetName',
            new_name='dataSet',
        ),
    ]
