# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20160211_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='size',
            field=models.CharField(choices=[('1', '1x'), ('2', '2x'), ('3', '3x')], help_text='size of your chart', max_length=2),
        ),
    ]
