# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_auto_20160211_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='options',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chart',
            name='dimensions',
            field=models.CharField(max_length=100),
        ),
    ]
