# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_auto_20160211_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='chart',
            field=models.ManyToManyField(related_name='DataWipTable', to='apis.Chart'),
        ),
    ]
